// <auto-generated />
namespace FilesUrl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addtypesize2filesurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtypesize2filesurl));
        
        string IMigrationMetadata.Id
        {
            get { return "202108181312267_Add-type&size-2-filesurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
